# Read the documentation: https://github.com/FriendsOfSymfony/FOSElasticaBundle/blob/master/Resources/doc/setup.md
fos_elastica:
    clients:
        default: { url: "%env(ELASTICSEARCH_URL)%" }
    indexes:
        marvel: # the name of our index
            settings:
                index:
                    analysis:
                        filter:
                            autocomplete_filter:
                                type: edge_ngram
                                min_gram: 1
                                max_gram: 20
                        analyzer:
                            keyword_analyzer: # this is a custom analyzer, see the explanations below
                                type: custom
                                tokenizer: standard
                                filter:
                                    [standard, lowercase, asciifolding, trim]
                            autocomplete:
                                type: custom
                                tokenizer: standard
                                filter:
                                    - lowercase
                                    - autocomplete_filter
            types:
                superhero: # the name of our type
                    properties:
                        name:
                            analyzer: autocomplete
                            search_analyzer: standard
                            type: text
                    persistence:
                        driver: orm
                        model: App\Entity\SuperHero
                        provider: ~
                        finder: ~
                        repository: App\SearchRepository\SuperHeroRepository
