version: '3'

services:

  mysql:
    image: mysql:5.7
    container_name: sandbox_es_db
    ports:
      - '3306:3306'
    networks:
      - 'esnet'
    environment:
      MYSQL_ROOT_PASSWORD: 'root'
      MYSQL_USER: 'search'
      MYSQL_PASSWORD: 'search'
      MYSQL_DATABASE: 'search'

  es01:
    image: elasticsearch:7.4.1
    container_name: sandbox_es_01
    environment:
      - node.name=es01
      - discovery.seed_hosts=es02
      - cluster.initial_master_nodes=es01,es02
      - cluster.name=docker-cluster
      - bootstrap.memory_lock=true
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
    ulimits:
      memlock:
        soft: -1
        hard: -1
    volumes:
      - esdata01:/usr/share/elasticsearch/data
    ports:
      - 9200:9200
    networks:
      - esnet

  es02:
    image: elasticsearch:7.4.1
    container_name: sandbox_es_02
    environment:
      - node.name=es02
      - discovery.seed_hosts=es01
      - cluster.initial_master_nodes=es01,es02
      - cluster.name=docker-cluster
      - bootstrap.memory_lock=true
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
    ulimits:
      memlock:
        soft: -1
        hard: -1
    volumes:
      - esdata02:/usr/share/elasticsearch/data
    networks:
      - esnet

volumes:
  esdata01:
    driver: local
  esdata02:
    driver: local

networks:
  esnet:
